"""Initial schema

Revision ID: b1a12f471951
Revises: 
Create Date: 2026-07-04 19:28:32.343461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1a12f471951'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permissions')
    op.drop_index('idx_audit_trail_row_id', table_name='audit_trail')
    op.drop_index('idx_audit_trail_table_action', table_name='audit_trail')
    op.drop_table('audit_trail')
    op.drop_index('idx_role_permissions_role', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('idx_audit_logs_action', table_name='audit_logs')
    op.drop_index('idx_audit_logs_user', table_name='audit_logs')
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.drop_index('idx_password_resets_token', table_name='password_resets')
    op.drop_constraint('password_resets_reset_token_hash_key', 'password_resets', type_='unique')
    op.create_index(op.f('ix_password_resets_reset_token_hash'), 'password_resets', ['reset_token_hash'], unique=True)
    op.drop_index('idx_profiles_names', table_name='profiles')
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.alter_column('user_sessions', 'token_family',
               existing_type=sa.UUID(),
               nullable=True,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_index('idx_sessions_refresh_token', table_name='user_sessions')
    op.drop_index('idx_sessions_user_id', table_name='user_sessions')
    op.drop_constraint('user_sessions_refresh_token_hash_key', 'user_sessions', type_='unique')
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=True)
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint('users_email_key', 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.create_unique_constraint('user_sessions_refresh_token_hash_key', 'user_sessions', ['refresh_token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_index('idx_sessions_refresh_token', 'user_sessions', ['refresh_token_hash'], unique=False)
    op.alter_column('user_sessions', 'token_family',
               existing_type=sa.UUID(),
               nullable=False,
               existing_server_default=sa.text('uuid_generate_v4()'))
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.create_index('idx_profiles_names', 'profiles', ['last_name', 'first_name'], unique=False)
    op.drop_index(op.f('ix_password_resets_reset_token_hash'), table_name='password_resets')
    op.create_unique_constraint('password_resets_reset_token_hash_key', 'password_resets', ['reset_token_hash'], postgresql_nulls_not_distinct=False)
    op.create_index('idx_password_resets_token', 'password_resets', ['reset_token_hash'], unique=False)
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.create_index('idx_audit_logs_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index('idx_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('permission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name='role_permissions_permission_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='role_permissions_role_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name='role_permissions_pkey')
    )
    op.create_index('idx_role_permissions_role', 'role_permissions', ['role_id'], unique=False)
    op.create_table('audit_trail',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('row_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('changed_by', sa.VARCHAR(length=100), server_default=sa.text('CURRENT_USER'), autoincrement=False, nullable=True),
    sa.Column('changed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='audit_trail_pkey')
    )
    op.create_index('idx_audit_trail_table_action', 'audit_trail', ['table_name', 'action'], unique=False)
    op.create_index('idx_audit_trail_row_id', 'audit_trail', ['row_id'], unique=False)
    op.create_table('permissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='permissions_pkey'),
    sa.UniqueConstraint('name', name='permissions_name_key', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
